import {
  appPromoData,
  blogData,
  faqsData,
  featuresData,
  footerData,
  newsletterData,
  portfolioData,
  signInSignUpData,
  statisticsData,
  teamData,
  testimonialData,
  textComponentData,
  // headerData,
  // howItWorksData,
  // logoCloudData,
  // navigationData,
  // callToActionData,
  // contactData,
} from "./data/schemas";

export const componentsData = {
  portfolio: portfolioData,
  testimonial: testimonialData,
  team: teamData,
  newsletter: newsletterData,
  faqs: faqsData,
  stats: statisticsData,
  appPromo: appPromoData,
  footer: footerData,
  signInSignUp: signInSignUpData,
  textComponent: textComponentData,
  features: featuresData,
  blog: blogData,
  // header: headerData,
  // callToAction: callToActionData,
  // contact: contactData,
  // navigation: navigationData,
  // logoCloud: logoCloudData,
  // howItWorks: howItWorksData,
  // cookies: cookiesData,
  // pricing: pricingData,
  //cartSection: {},
  //featuredProducts: {},
  //productInfo: {},
  //wishlistSection: {},
  //pages_productInfo: {},
  //allProducts: {},
  //socialMediaFeed: {},
};
