import {
  appPromoData,
  blogData,
  callToActionData,
  contactData,
  faqsData,
  featuresData,
  footerData,
  headerData,
  howItWorksData,
  logoCloudData,
  // navigationData,
  newsletterData,
  portfolioData,
  signInSignUpData,
  statisticsData,
  teamData,
  testimonialData,
  textComponentData,
} from "./data/schemas";

export const componentsData = {
  // navigation: navigationData,
  header: headerData,
  features: featuresData,
  portfolio: portfolioData,
  blog: blogData,
  contact: contactData,
  testimonial: testimonialData,
  team: teamData,
  howItWorks: howItWorksData,
  newsletter: newsletterData,
  faqs: faqsData,
  callToAction: callToActionData,
  stats: statisticsData,
  appPromo: appPromoData,
  logoCloud: logoCloudData,
  footer: footerData,
  signInSignUp: signInSignUpData,
  textComponent: textComponentData,
  // cookies: cookiesData,
  // pricing: pricingData,
  //cartSection: {},
  //featuredProducts: {},
  //productInfo: {},
  //wishlistSection: {},
  //pages_productInfo: {},
  //allProducts: {},
  //socialMediaFeed: {},
};
