#!/usr/bin/env bash
# notify-publishforge.sh — trigger PublishForge to (re)generate the /agents/<slug> page
# for a published `page` or `post` document. Exit 0 = PF accepted (pipeline started),
# non-zero = nothing will be generated (missing doc, ignored payload, or proxy error).
#
# Usage:
#   scripts/notify-publishforge.sh <slug>                      # resolve _id/_type by slug (GROQ)
#   scripts/notify-publishforge.sh <slug> <documentId> <type>  # skip the lookup (type: page|post)
#
# WHY THIS EXISTS
#   Agents pages are generated by PublishForge, which must be TOLD a document was
#   published. The existing triggers: (1) the Studio publish action (browser) and
#   (2) CiteForge's migration callback on a CI run's "done" ping. A LOCAL/CLI
#   migration (stackshift-section skill run outside CI) hits neither — this script
#   is that third trigger, called by the skill's post-verdict step (SKILL.md, after
#   G7 Verdict: DONE) or by hand after publishing content via the mutate API.
#
# ZERO-SECRET DESIGN (same as CiteForge lib/publishforge/notify.ts): we never hold
# PUBLISHFORGE_WEBHOOK_SECRET — the deployed site's /api/publishforge-proxy owns it
# and injects the x-publishforge-webhook-secret header. Only public reads happen here.
#
# CI GUARD: in GitHub Actions this exits 0 without notifying — CiteForge already
# notifies on the run's "done" callback (migration-callback/route.ts), and firing
# here too would run the PF pipeline twice per migration.
#
# Requires: bash, curl, python3. Reads NEXT_PUBLIC_SANITY_* / NEXT_PUBLIC_SITE_URL
# from env or .env.local/.env.development.
set -u

if [ -n "${GITHUB_ACTIONS:-}" ]; then
  echo "SKIP: CI run — CiteForge notifies PublishForge on the done callback (no double-fire)."
  exit 0
fi

SLUG="${1:-}"
DOC_ID="${2:-}"
DOC_TYPE="${3:-}"
if [ -z "$SLUG" ]; then
  echo "usage: scripts/notify-publishforge.sh <slug> [<documentId> <page|post>]" >&2
  exit 2
fi

# creds/config: env first, then whichever env file exists (CLAUDE.md §3)
set -a; . ./.env.local 2>/dev/null; . ./.env.development 2>/dev/null; set +a
PROJECT="${NEXT_PUBLIC_SANITY_PROJECT_ID:-mhz4l0xy}"
DATASET="${NEXT_PUBLIC_SANITY_DATASET:-production}"
# Proxy target: PF_PROXY_BASE_URL (explicit override) > NEXT_PUBLIC_SITE_URL (env/.env files).
# No hardcoded fallback — the domain is per-project config, not code. CAVEAT: in .env.local
# NEXT_PUBLIC_SITE_URL is usually localhost; that works ONLY if the dev server is running AND
# holds PUBLISHFORGE_WEBHOOK_SECRET — otherwise set PF_PROXY_BASE_URL to the deployed site.
SITE_URL="${PF_PROXY_BASE_URL:-${NEXT_PUBLIC_SITE_URL:-}}"
SITE_URL="${SITE_URL%/}"
if [ -z "$SITE_URL" ]; then
  echo "FAIL: no proxy target — set NEXT_PUBLIC_SITE_URL (or PF_PROXY_BASE_URL) in the env / .env.local." >&2
  exit 2
fi
case "$SITE_URL" in *localhost*|*127.0.0.1*)
  echo "NOTE: proxy target is $SITE_URL (from NEXT_PUBLIC_SITE_URL) — the dev server must be running with PUBLISHFORGE_WEBHOOK_SECRET set, or export PF_PROXY_BASE_URL=<deployed site URL>."
esac

if [ -z "$DOC_ID" ]; then
  # Resolve the PUBLISHED doc (drafts excluded — PF ignores drafts as not-found).
  # Read token optional: the dataset is publicly readable; send auth only if present.
  AUTH=()
  [ -n "${NEXT_PUBLIC_SANITY_API_READ_TOKEN:-}" ] && AUTH=(-H "Authorization: Bearer $NEXT_PUBLIC_SANITY_API_READ_TOKEN")
  RESP="$(curl -sG "https://$PROJECT.api.sanity.io/v2022-03-13/data/query/$DATASET" \
    "${AUTH[@]}" \
    --data-urlencode 'query=*[slug.current == $slug && _type in ["page","post"] && !(_id in path("drafts.**"))][0]{_id,_type}' \
    --data-urlencode "\$slug=\"$SLUG\"")"
  DOC_ID="$(printf '%s' "$RESP" | python3 -c 'import sys,json; d=json.load(sys.stdin).get("result") or {}; print(d.get("_id",""))')"
  DOC_TYPE="$(printf '%s' "$RESP" | python3 -c 'import sys,json; d=json.load(sys.stdin).get("result") or {}; print(d.get("_type",""))')"
  if [ -z "$DOC_ID" ]; then
    echo "FAIL: no PUBLISHED page/post with slug '$SLUG' in $PROJECT/$DATASET — publish it first." >&2
    exit 1
  fi
fi

BODY="$(python3 -c 'import json,sys; print(json.dumps({"documentId":sys.argv[1],"documentType":sys.argv[2],"slug":sys.argv[3]}))' "$DOC_ID" "$DOC_TYPE" "$SLUG")"
HTTP="$(curl -s -o /tmp/pf-notify-resp.json -w '%{http_code}' -m 30 -X POST \
  "$SITE_URL/api/publishforge-proxy" -H "Content-Type: application/json" -d "$BODY")"
echo "POST $SITE_URL/api/publishforge-proxy → $HTTP"
cat /tmp/pf-notify-resp.json 2>/dev/null; echo

case "$HTTP" in
  2*) : ;;
  000)
    echo "FAIL: proxy unreachable at $SITE_URL — PublishForge was NOT triggered. If that's a localhost URL, start the dev server or export PF_PROXY_BASE_URL=<deployed site URL>." >&2
    exit 1
    ;;
  *)
    echo "FAIL: proxy returned $HTTP — PublishForge was NOT triggered." >&2
    exit 1
esac
# "accepted but ignored" (e.g. sanity_document_not_found) produces no agents page — surface it.
if python3 -c 'import json,sys; sys.exit(0 if json.load(open("/tmp/pf-notify-resp.json")).get("ignored") else 1)' 2>/dev/null; then
  echo "FAIL: PublishForge IGNORED the payload (see reason above) — no agents page will be generated." >&2
  exit 1
fi
echo "PASS: PublishForge pipeline triggered for $DOC_TYPE '$SLUG' ($DOC_ID)."
echo "      Expect a 'publish: $SLUG' commit on master within ~1-3 min, then /agents/$SLUG after the Vercel deploy."
