// Dev-only: writes sample agent markdown files into content/agents/ so the agent
// route, llms.txt generator, and sitemap-agents.xml generator can be tested without
// waiting for PublishForge / GitHub App wiring. Files are prefixed `__fixture-`
// and gitignored — they will not be committed.
//
// Usage: yarn seed:agents
// Cleanup: yarn clean:agents

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const TARGET_DIR = path.join(process.cwd(), "content", "agents");

const FIXTURES: Array<{ filename: string; content: string }> = [
  {
    filename: "__fixture-basic.md",
    content: `---
title: Basic Fixture Agent
slug: __fixture-basic
summary: A minimal agent page used to verify rendering, llms.txt, and sitemap generation.
generated_at: 2026-05-24T12:00:00Z
taxonomy: article
---

# Overview

This is a **dev-only fixture** generated by \`yarn seed:agents\`. It exercises the
baseline Article JSON-LD branch.

## What it tests

- Frontmatter parsing
- Markdown body rendering (headings, lists, emphasis)
- Article JSON-LD baseline (no FAQPage)
- Entry in \`public/llms.txt\`
- Entry in \`public/sitemap-agents.xml\`

Run \`yarn clean:agents\` to remove this file.
`,
  },
  {
    filename: "__fixture-with-faq.md",
    content: `---
title: Fixture Agent With FAQ
slug: __fixture-with-faq
summary: Verifies the FAQPage JSON-LD branch triggers when frontmatter has an faq array.
generated_at: 2026-05-24T12:00:00Z
taxonomy: article
faq:
  - q: What is this fixture for?
    a: Verifying that the FAQPage JSON-LD branch fires correctly during static generation.
  - q: Will this be deployed to production?
    a: No. Files matching __fixture-*.md are gitignored and only exist locally.
  - q: How do I clean up?
    a: Run yarn clean:agents.
---

# FAQ Fixture

This fixture verifies that the JSON-LD output includes a nested **FAQPage**
\`mainEntity\` with one Question/Answer pair per item in the \`faq\` array.

## Body content

Some additional markdown body to confirm the renderer still runs alongside the
FAQ branch.
`,
  },
];

async function main() {
  await mkdir(TARGET_DIR, { recursive: true });

  for (const fixture of FIXTURES) {
    const absPath = path.join(TARGET_DIR, fixture.filename);
    await writeFile(absPath, fixture.content, "utf-8");
    console.log(`[seed-agents-fixtures] wrote ${absPath}`);
  }

  console.log(`[seed-agents-fixtures] ${FIXTURES.length} fixtures written.`);
  console.log("Next: yarn dev (or yarn build) to render them.");
}

main().catch((err) => {
  console.error("[seed-agents-fixtures] failed:", err);
  process.exit(1);
});
